interface BoardPosition {
  row: number;
  column: number;
  isCorner?: boolean;
  rank?: string;
  suit?: string;
}

export const BOARD_DATA: (BoardPosition | null)[][] = [
  [
    { row: 1, column: 1, isCorner: true },
    { row: 1, column: 2, rank: "ace", suit: "clubs" },
    { row: 1, column: 3, rank: "king", suit: "clubs" },
    { row: 1, column: 4, rank: "queen", suit: "clubs" },
    { row: 1, column: 5, rank: "10", suit: "clubs" },
    { row: 1, column: 6, rank: "9", suit: "clubs" },
    { row: 1, column: 7, rank: "8", suit: "clubs" },
    { row: 1, column: 8, rank: "7", suit: "clubs" },
    { row: 1, column: 9, rank: "6", suit: "clubs" },
    { row: 1, column: 10, isCorner: true },
  ],
  [
    { row: 2, column: 1, rank: "ace", suit: "diamonds" },
    { row: 2, column: 2, rank: "7", suit: "spades" },
    { row: 2, column: 3, rank: "8", suit: "spades" },
    { row: 2, column: 4, rank: "9", suit: "spades" },
    { row: 2, column: 5, rank: "10", suit: "spades" },
    { row: 2, column: 6, rank: "queen", suit: "spades" },
    { row: 2, column: 7, rank: "king", suit: "spades" },
    { row: 2, column: 8, rank: "ace", suit: "spades" },
    { row: 2, column: 9, rank: "5", suit: "clubs" },
    { row: 2, column: 10, rank: "2", suit: "spades" },
  ],
  // Row 2 (3-indexed in game)
  [
    { row: 3, column: 1, rank: "king", suit: "diamonds" },
    { row: 3, column: 2, rank: "6", suit: "spades" },
    { row: 3, column: 3, rank: "10", suit: "clubs" },
    { row: 3, column: 4, rank: "9", suit: "clubs" },
    { row: 3, column: 5, rank: "8", suit: "clubs" },
    { row: 3, column: 6, rank: "7", suit: "clubs" },
    { row: 3, column: 7, rank: "6", suit: "clubs" },
    { row: 3, column: 8, rank: "2", suit: "diamonds" },
    { row: 3, column: 9, rank: "4", suit: "clubs" },
    { row: 3, column: 10, rank: "3", suit: "spades" },
  ],
  [
    { row: 4, column: 1, rank: "queen", suit: "diamonds" },
    { row: 4, column: 2, rank: "5", suit: "spades" },
    { row: 4, column: 3, rank: "queen", suit: "clubs" },
    { row: 4, column: 4, rank: "8", suit: "hearts" },
    { row: 4, column: 5, rank: "7", suit: "hearts" },
    { row: 4, column: 6, rank: "6", suit: "hearts" },
    { row: 4, column: 7, rank: "5", suit: "clubs" },
    { row: 4, column: 8, rank: "3", suit: "diamonds" },
    { row: 4, column: 9, rank: "3", suit: "clubs" },
    { row: 4, column: 10, rank: "4", suit: "spades" },
  ],
  [
    { row: 5, column: 1, rank: "10", suit: "diamonds" },
    { row: 5, column: 2, rank: "4", suit: "spades" },
    { row: 5, column: 3, rank: "king", suit: "clubs" },
    { row: 5, column: 4, rank: "9", suit: "hearts" },
    { row: 5, column: 5, rank: "2", suit: "hearts" },
    { row: 5, column: 6, rank: "5", suit: "hearts" },
    { row: 5, column: 7, rank: "4", suit: "clubs" },
    { row: 5, column: 8, rank: "4", suit: "diamonds" },
    { row: 5, column: 9, rank: "2", suit: "clubs" },
    { row: 5, column: 10, rank: "5", suit: "spades" },
  ],
  [
    { row: 6, column: 1, rank: "9", suit: "diamonds" },
    { row: 6, column: 2, rank: "3", suit: "spades" },
    { row: 6, column: 3, rank: "ace", suit: "clubs" },
    { row: 6, column: 4, rank: "10", suit: "hearts" },
    { row: 6, column: 5, rank: "3", suit: "hearts" },
    { row: 6, column: 6, rank: "4", suit: "hearts" },
    { row: 6, column: 7, rank: "3", suit: "clubs" },
    { row: 6, column: 8, rank: "5", suit: "diamonds" },
    { row: 6, column: 9, rank: "ace", suit: "hearts" },
    { row: 6, column: 10, rank: "6", suit: "spades" },
  ],
  [
    { row: 7, column: 1, rank: "8", suit: "diamonds" },
    { row: 7, column: 2, rank: "2", suit: "spades" },
    { row: 7, column: 3, rank: "ace", suit: "diamonds" },
    { row: 7, column: 4, rank: "queen", suit: "hearts" },
    { row: 7, column: 5, rank: "king", suit: "hearts" },
    { row: 7, column: 6, rank: "ace", suit: "hearts" },
    { row: 7, column: 7, rank: "2", suit: "clubs" },
    { row: 7, column: 8, rank: "6", suit: "diamonds" },
    { row: 7, column: 9, rank: "king", suit: "hearts" },
    { row: 7, column: 10, rank: "7", suit: "spades" },
  ],
  [
    { row: 8, column: 1, rank: "7", suit: "diamonds" },
    { row: 8, column: 2, rank: "2", suit: "hearts" },
    { row: 8, column: 3, rank: "king", suit: "diamonds" },
    { row: 8, column: 4, rank: "queen", suit: "diamonds" },
    { row: 8, column: 5, rank: "10", suit: "diamonds" },
    { row: 8, column: 6, rank: "9", suit: "diamonds" },
    { row: 8, column: 7, rank: "8", suit: "diamonds" },
    { row: 8, column: 8, rank: "7", suit: "diamonds" },
    { row: 8, column: 9, rank: "queen", suit: "hearts" },
    { row: 8, column: 10, rank: "8", suit: "spades" },
  ],
  [
    { row: 9, column: 1, rank: "6", suit: "diamonds" },
    { row: 9, column: 2, rank: "3", suit: "hearts" },
    { row: 9, column: 3, rank: "4", suit: "hearts" },
    { row: 9, column: 4, rank: "5", suit: "hearts" },
    { row: 9, column: 5, rank: "6", suit: "hearts" },
    { row: 9, column: 6, rank: "7", suit: "hearts" },
    { row: 9, column: 7, rank: "8", suit: "hearts" },
    { row: 9, column: 8, rank: "9", suit: "hearts" },
    { row: 9, column: 9, rank: "10", suit: "hearts" },
    { row: 9, column: 10, rank: "9", suit: "spades" },
  ],
  [
    { row: 10, column: 1, isCorner: true },
    { row: 10, column: 2, rank: "5", suit: "diamonds" },
    { row: 10, column: 3, rank: "4", suit: "diamonds" },
    { row: 10, column: 4, rank: "3", suit: "diamonds" },
    { row: 10, column: 5, rank: "2", suit: "diamonds" },
    { row: 10, column: 6, rank: "ace", suit: "spades" },
    { row: 10, column: 7, rank: "king", suit: "spades" },
    { row: 10, column: 8, rank: "queen", suit: "spades" },
    { row: 10, column: 9, rank: "10", suit: "spades" },
    { row: 10, column: 10, isCorner: true },
  ],
];
